project:
  type: website
  output-dir: docs

website:
  title: "Derechos de la infancia en Chile"
  navbar:
    left:
      - href: index.qmd
        text: "Panorama"
      - href: metodologia.qmd
        text: "Metodolog√≠a"

format:
  html:
    toc: false
    smooth-scroll: true
