format:
  html:
    toc: false
    smooth-scroll: true
    theme:
      - cosmo
      - styles.scss
    code-fold: false
    code-tools: false
    execute:
      echo: false
      warning: false
      message: false

